apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bot-dev-test
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
images:
  - name: ghcr.io/script-repo/bot-dev-test
    newTag: latest
